# Database schema - table structure
CREATE_QUERIES = {
    "country": """CREATE TABLE IF NOT EXISTS country (
        country_code varchar(10) PRIMARY KEY,
        country_name varchar(100) NOT NULL,
        crs varchar(20) DEFAULT 'EPSG:3035',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """,
    "state": """CREATE TABLE IF NOT EXISTS state (
        state_id SERIAL PRIMARY KEY,
        state_code varchar(50) NOT NULL,
        state_name varchar(100) NOT NULL,
        country_code varchar(10) NOT NULL,
        osm_relation_id bigint,
        nuts_code varchar(10),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT uq_state_country UNIQUE (state_code, country_code),
        CONSTRAINT fk_state_country
            FOREIGN KEY (country_code)
            REFERENCES country (country_code)
            ON DELETE CASCADE
    )
    """,
    "version": """CREATE TABLE IF NOT EXISTS version (
        version_id varchar(10) PRIMARY KEY,
        version_comment varchar, 
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        consumer_categories varchar,
        connection_available_cables varchar,   
        other_parameters varchar
    )
    """,
    "equipment_data": """
   CREATE TABLE IF NOT EXISTS equipment_data(
       version_id       varchar(10)  NOT NULL,
       name             varchar(100) NOT NULL,
       s_max_kva        integer,
       max_i_a          integer,
       r_mohm_per_km    integer,
       x_mohm_per_km    integer,
       z_mohm_per_km    integer,
       cost_eur         integer,
       equipment_only_cost_eur integer,
       installed_cost_eur integer,
       typ              varchar(50),
       CONSTRAINT equipment_data_pkey PRIMARY KEY (version_id, name),
       CONSTRAINT fk_equipment_data_version
           FOREIGN KEY (version_id)
               REFERENCES version (version_id)
               ON DELETE CASCADE
   )
    """,
    "classification_version": """
    CREATE TABLE IF NOT EXISTS classification_version (
        classification_id integer NOT NULL,
        classification_version_comment varchar, 
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        classification_region varchar,
        CONSTRAINT classification_pkey PRIMARY KEY (classification_id)
    )
    """,
    "postcode": """
    CREATE TABLE IF NOT EXISTS postcode (
        postcode_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        plz varchar(10) NOT NULL,
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        state_code varchar(50),
        allocated_plz varchar(10),
        note varchar,
        qkm double precision,
        population integer,
        cbs_households double precision,
        cbs_avg_household_size double precision,
        geom geometry(MultiPolygon,3035),
        CONSTRAINT postcode_pkey PRIMARY KEY (postcode_id),
        CONSTRAINT uq_plz_country UNIQUE (plz, country_code),
        CONSTRAINT fk_postcode_country
            FOREIGN KEY (country_code)
            REFERENCES country (country_code)
            ON DELETE CASCADE,
        CONSTRAINT fk_postcode_state_country
            FOREIGN KEY (state_code, country_code)
            REFERENCES state (state_code, country_code)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_postcode_geom ON postcode USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_postcode_country ON postcode (country_code);
    CREATE INDEX IF NOT EXISTS idx_postcode_state ON postcode (state_code);
    CREATE INDEX IF NOT EXISTS idx_postcode_country_state ON postcode (country_code, state_code);
    CREATE INDEX IF NOT EXISTS idx_postcode_plz ON postcode (plz)
    """,
    "postcode_result": """
    CREATE TABLE IF NOT EXISTS postcode_result (   
        version_id varchar(10) NOT NULL,
        postcode_result_plz varchar(10) NOT NULL,
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        state_code varchar(50),
        geom geometry(MultiPolygon,3035),
        house_distance double precision,
        avg_households_per_building double precision,
        settlement_type integer,
        
        CONSTRAINT postcode_result_pkey PRIMARY KEY (version_id, postcode_result_plz, country_code),
        CONSTRAINT fk_postcode_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_postcode_result_plz_country
            FOREIGN KEY (postcode_result_plz, country_code)
            REFERENCES postcode (plz, country_code)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_postcode_result_geom ON postcode_result USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_postcode_result_country_state ON postcode_result (country_code, state_code);
    """,
    "grid_result": """
    CREATE TABLE IF NOT EXISTS grid_result (
        grid_result_id SERIAL PRIMARY KEY,
        version_id varchar(10) NOT NULL,
        kcid integer NOT NULL,
        bcid integer NOT NULL,
        plz varchar(10) NOT NULL,
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        transformer_rated_power bigint,
        transformer_equipment_name varchar(100),
        transformer_description varchar(100),
        model_status integer,
        ont_vertice_id bigint,
        grid json,
        CONSTRAINT cluster_identifier UNIQUE (version_id, kcid, bcid, plz, country_code),
        CONSTRAINT unique_grid_result_id_version_id UNIQUE (version_id, grid_result_id),
        CONSTRAINT fk_grid_result_version_id_plz_country
            FOREIGN KEY (version_id, plz, country_code)
            REFERENCES postcode_result (version_id, postcode_result_plz, country_code)
            ON DELETE CASCADE,
        CONSTRAINT fk_grid_result_transformer_equipment
            FOREIGN KEY (version_id, transformer_equipment_name)
            REFERENCES equipment_data(version_id, name)
            ON DELETE SET NULL
    );
    CREATE INDEX IF NOT EXISTS idx_grid_result_version_id_plz_bcid_kcid
    ON grid_result (version_id, plz, country_code, bcid, kcid);
    CREATE INDEX IF NOT EXISTS idx_grid_result_version_plz_kcid
    ON grid_result (version_id, plz, kcid);
    CREATE INDEX IF NOT EXISTS idx_grid_result_version
    ON grid_result (version_id);
    CREATE INDEX IF NOT EXISTS idx_grid_result_plz_cc
    ON grid_result (plz, country_code);
    """,
    "lines_result": """
    CREATE TABLE IF NOT EXISTS lines_result (
        lines_result_id SERIAL PRIMARY KEY,
        grid_result_id bigint NOT NULL,
        geom geometry(LineString,3035),
        line_name varchar(50),
        std_type varchar(50),
        from_bus integer,
        to_bus integer,
        length_km double precision,
        CONSTRAINT fk_lines_result_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_lines_result_grid_result_id ON lines_result (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_lines_result_geom ON lines_result USING GIST (geom)
    """,
    "consumer_categories": """
    CREATE TABLE IF NOT EXISTS consumer_categories (
        consumer_category_id integer PRIMARY KEY,
        definition varchar(80) UNIQUE NOT NULL,
        load_method varchar(20) NOT NULL DEFAULT 'area',
        parent_category varchar(30) NOT NULL DEFAULT 'commercial',
        peak_load double precision,
        yearly_consumption double precision,
        peak_load_per_m2 double precision,
        yearly_consumption_per_m2 double precision,
        sim_factor double precision NOT NULL
    )
    """,
    "buildings_result": """
    CREATE TABLE IF NOT EXISTS buildings_result (
        version_id varchar(10) NOT NULL,
        osm_id varchar NOT NULL,
        grid_result_id bigint NOT NULL,
        area double precision,
        type varchar(80),
        f_class varchar(80),
        f_classes text,
        geom geometry(MultiPolygon,3035),
        households_per_building integer,
        center geometry(Point,3035),
        peak_load_in_kw double precision,
        vertice_id integer,
        floors integer,
        construction_year text,
        connection_point integer,
        height_max double precision,
        height_ground double precision,
        height_median double precision,
        floors_3dbag integer,
        bag_id varchar,
        energy_label varchar(5),
        energy_index double precision,
        cbs_population double precision,
        cbs_households double precision,
        cbs_avg_household_size double precision,
        CONSTRAINT buildings_result_pkey PRIMARY KEY (version_id, osm_id),
        CONSTRAINT fk_buildings_result_grid_result
            FOREIGN KEY (version_id, grid_result_id)
            REFERENCES grid_result (version_id, grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_buildings_result_grid_result_id
    ON buildings_result (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_buildings_result_grid_version
    ON buildings_result (grid_result_id, version_id);
    CREATE INDEX IF NOT EXISTS idx_buildings_result_geom
    ON buildings_result USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_buildings_result_center
    ON buildings_result USING GIST (center);
    """,
    "municipal_register": """CREATE TABLE IF NOT EXISTS municipal_register (
        plz varchar(10),
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        state_code varchar(50),
        pop bigint,
        area double precision,
        lat double precision,
        lon double precision,
        ags varchar(20),
        name_city text,
        fed_state varchar(50),
        regio7 integer,
        regio5 integer,
        pop_den double precision,
        CONSTRAINT municipal_register_pkey PRIMARY KEY (plz, country_code, ags),
        CONSTRAINT fk_municipal_register_country
            FOREIGN KEY (country_code)
            REFERENCES country (country_code)
            ON DELETE CASCADE
    )
    """,
    "sample_set": """CREATE TABLE IF NOT EXISTS sample_set (
        classification_id integer NOT NULL,
        plz varchar(10) NOT NULL,
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        ags varchar(20),
        bin_no integer,
        bins double precision,
        perc_bin double precision,
        count double precision,
        perc double precision,
        CONSTRAINT sample_set_pkey PRIMARY KEY (classification_id, plz, country_code),
        CONSTRAINT fk_sample_set_classification_id
            FOREIGN KEY (classification_id)
            REFERENCES classification_version (classification_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_sample_set_plz
            FOREIGN KEY (plz, country_code, ags)
            REFERENCES municipal_register (plz, country_code, ags)
            ON DELETE CASCADE
    )
    """,
    "clustering_parameters": """CREATE TABLE IF NOT EXISTS clustering_parameters (
        grid_result_id bigint PRIMARY KEY,
        
        no_connection_buses integer,
        no_branches integer,
        
        no_house_connections integer,
        no_house_connections_per_branch double precision,
        no_households integer,
        no_household_equ double precision,
        no_households_per_branch double precision,
        max_no_of_households_of_a_branch double precision,
        house_distance_km double precision,
        
        transformer_mva double precision,
        osm_trafo bool,
        
        max_trafo_dis double precision,
        avg_trafo_dis double precision,
        
        cable_length_km double precision,
        cable_len_per_house double precision,
        
        max_power_mw double precision,
        simultaneous_peak_load_mw double precision,
        
        resistance double precision,
        reactance double precision,
        ratio double precision,
        vsw_per_branch double precision,
        max_vsw_of_a_branch double precision,
        
        filtered boolean,
        CONSTRAINT fk_clustering_parameters_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "transformers": """CREATE TABLE IF NOT EXISTS transformers (
        osm_id varchar PRIMARY KEY,
        country_code varchar(10) DEFAULT 'DE',
        state_code varchar(50),
        area double precision,
        type varchar,
        transformer_rated_power integer,
        geom_type varchar,
        within_shopping boolean,
        geom geometry(MultiPoint, 3035)
    );
    CREATE INDEX IF NOT EXISTS idx_transformers_geom ON transformers USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_transformers_state ON transformers (state_code);
    CREATE INDEX IF NOT EXISTS idx_transformers_country_state ON transformers (country_code, state_code);
    """,
    "transformer_positions": """
    CREATE TABLE IF NOT EXISTS transformer_positions (
        grid_result_id bigint PRIMARY KEY,
        geom geometry(Point,3035),
        osm_id varchar,
        version_id varchar(10),
        "comment" varchar,
        CONSTRAINT uq_tp_osm_v UNIQUE (osm_id, version_id),
        CONSTRAINT fk_tp_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_tp_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_tp_osm_id
            FOREIGN KEY (osm_id)
            REFERENCES transformers (osm_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_transformer_positions_geom ON transformer_positions USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_transformer_positions_version ON transformer_positions (version_id)
    """,
    "building_transformer_assignments": """
    CREATE TABLE IF NOT EXISTS building_transformer_assignments (
        assignment_id SERIAL PRIMARY KEY,
        building_osm_id VARCHAR NOT NULL,
        grid_result_id BIGINT NOT NULL,
        user_id VARCHAR(255),
        model_id INTEGER,
        draft_id VARCHAR(255),
        version_id VARCHAR(10) DEFAULT '1',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_bta_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_bta_building ON building_transformer_assignments (building_osm_id);
    CREATE INDEX IF NOT EXISTS idx_bta_model ON building_transformer_assignments (model_id);
    CREATE INDEX IF NOT EXISTS idx_bta_draft ON building_transformer_assignments (draft_id);
    CREATE INDEX IF NOT EXISTS idx_bta_user ON building_transformer_assignments (user_id);
    CREATE INDEX IF NOT EXISTS idx_bta_grid_result_id ON building_transformer_assignments (grid_result_id);
    CREATE INDEX IF NOT EXISTS idx_bta_building_grid ON building_transformer_assignments (building_osm_id, grid_result_id);
    """,
    "transformer_classified": """
    CREATE TABLE IF NOT EXISTS transformer_classified (
        grid_result_id bigint NOT NULL,
        geom geometry(Point,3035),
        kmedoid_clusters integer,
        kmedoid_representative_grid bool,
        kmeans_clusters integer,
        kmeans_representative_grid bool,
        gmm_clusters integer,
        gmm_representative_grid bool,
        classification_id integer NOT NULL,
        CONSTRAINT pk_grid_result_id PRIMARY KEY (grid_result_id, classification_id),
        CONSTRAINT fk_transformer_classified_classification_id
            FOREIGN KEY (classification_id)
            REFERENCES classification_version (classification_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_transformer_classified_grid_result
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "ags_log": """
    CREATE TABLE IF NOT EXISTS ags_log (
        ags varchar(20) PRIMARY KEY,
        country_code varchar(10) NOT NULL DEFAULT 'DE'
    )
    """,
    "ways": """
    CREATE TABLE IF NOT EXISTS ways (
        clazz integer,
        source integer,
        target integer,
        cost double precision,
        reverse_cost double precision,
        geom geometry(LineString,3035),
        way_id integer PRIMARY KEY,
        country_code varchar(10) DEFAULT 'DE',
        state_code varchar(50)
    );
    CREATE INDEX IF NOT EXISTS idx_ways_geom ON ways USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_ways_country ON ways (country_code);
    CREATE INDEX IF NOT EXISTS idx_ways_state ON ways (state_code);
    CREATE INDEX IF NOT EXISTS idx_ways_country_state ON ways (country_code, state_code);
    CREATE INDEX IF NOT EXISTS idx_ways_source ON ways (source);
    CREATE INDEX IF NOT EXISTS idx_ways_target ON ways (target);
    CREATE INDEX IF NOT EXISTS idx_ways_source_target ON ways (source, target)
    """,
    "ways_result": """
    CREATE TABLE IF NOT EXISTS ways_result (
        version_id varchar(10) NOT NULL,
        clazz integer,
        source integer,
        target integer,
        cost double precision,
        reverse_cost double precision,
        geom geometry(LineString,3035),
        way_id integer NOT NULL,
        plz varchar(10),
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        CONSTRAINT pk_ways_result PRIMARY KEY (version_id, way_id, plz, country_code),
        CONSTRAINT fk_ways_result_version_id_plz_country
            FOREIGN KEY (version_id, plz, country_code)
            REFERENCES postcode_result (version_id, postcode_result_plz, country_code)
            ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_ways_result_geom ON ways_result USING GIST (geom)
    """,
    "plz_parameters": """
    CREATE TABLE IF NOT EXISTS plz_parameters (
        version_id varchar(10) NOT NULL,
        plz varchar(10) NOT NULL,
        country_code varchar(10) NOT NULL DEFAULT 'DE',
        trafo_num json,
        cable_length json,
        load_count_per_trafo json,
        bus_count_per_trafo json,
        sim_peak_load_per_trafo json,
        max_distance_per_trafo json,
        avg_distance_per_trafo json,
        CONSTRAINT parameters_pkey PRIMARY KEY (version_id, plz, country_code),
        CONSTRAINT fk_plz_parameters_version_id_plz_country
            FOREIGN KEY (version_id, plz, country_code)
            REFERENCES postcode_result (version_id, postcode_result_plz, country_code)
            ON DELETE CASCADE
    )
    """,
    "res": """CREATE TABLE IF NOT EXISTS res
                   (
                       osm_id     varchar NOT NULL,
                       country_code varchar(10) NOT NULL DEFAULT 'DE',
                       state_code varchar(50),
                       area       double precision,
                       use        varchar(80),
                       comment    varchar(80),
                       free_walls integer,
                       building_t varchar(80),
                       occupants  double precision,
                       floors     integer,
                       constructi varchar(80),
                       refurb_wal double precision,
                       refurb_roo double precision,
                       refurb_bas double precision,
                       refurb_win double precision,
                       f_class    varchar(80) NOT NULL DEFAULT 'yes',
                       f_classes  text,
                       geom       geometry(MultiPolygon, 3035),
                       height_max      double precision,
                       height_ground   double precision,
                       height_median   double precision,
                       floors_3dbag    integer,
                       bag_id          varchar,
                       energy_label    varchar(5),
                       energy_index    double precision,
                       cbs_population  double precision,
                       cbs_households  double precision,
                       cbs_avg_household_size double precision,
                       PRIMARY KEY (osm_id, f_class, country_code)
                   );
    CREATE INDEX IF NOT EXISTS idx_res_geom ON res USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_res_country ON res (country_code);
    CREATE INDEX IF NOT EXISTS idx_res_state ON res (state_code);
    CREATE INDEX IF NOT EXISTS idx_res_country_state ON res (country_code, state_code);
    CREATE INDEX IF NOT EXISTS idx_res_osm_id ON res (osm_id)
    """,
    "oth": """CREATE TABLE IF NOT EXISTS oth
                               (
                                   osm_id     varchar NOT NULL,
                                   country_code varchar(10) NOT NULL DEFAULT 'DE',
                                   state_code varchar(50),
                                   area       double precision,
                                   use        varchar(80),
                                   comment    varchar(80),
                                   free_walls integer,
                                   f_class    varchar(80) NOT NULL DEFAULT 'yes',
                                   f_classes  text,
                                   geom       geometry(MultiPolygon, 3035),
                                   height_max      double precision,
                                   height_ground   double precision,
                                   height_median   double precision,
                                   floors_3dbag    integer,
                                   bag_id          varchar,
                                   cbs_population  double precision,
                                   cbs_households  double precision,
                                   cbs_avg_household_size double precision,
                                   PRIMARY KEY (osm_id, f_class, country_code)
                               );
    CREATE INDEX IF NOT EXISTS idx_oth_geom ON oth USING GIST (geom);
    CREATE INDEX IF NOT EXISTS idx_oth_country ON oth (country_code);
    CREATE INDEX IF NOT EXISTS idx_oth_state ON oth (state_code);
    CREATE INDEX IF NOT EXISTS idx_oth_country_state ON oth (country_code, state_code);
    CREATE INDEX IF NOT EXISTS idx_oth_osm_id ON oth (osm_id)
    """,
    "transformer_positions_with_grid": """CREATE MATERIALIZED VIEW IF NOT EXISTS transformer_positions_with_grid AS (
        SELECT 
            tp.*,
            gr.kcid,
            gr.bcid,
            gr.plz,
            gr.country_code,
            gr.transformer_rated_power,
            gr.transformer_equipment_name,
            ed.s_max_kva,
            ed.max_i_a,
            ed.r_mohm_per_km,
            ed.x_mohm_per_km,
            ed.z_mohm_per_km,
            ed.cost_eur,
            ed.equipment_only_cost_eur,
            ed.installed_cost_eur,
            ed.typ AS equipment_type
        FROM transformer_positions tp
        JOIN grid_result gr ON tp.grid_result_id = gr.grid_result_id
        LEFT JOIN equipment_data ed 
            ON gr.version_id = ed.version_id 
            AND gr.transformer_equipment_name = ed.name
    );
    CREATE INDEX IF NOT EXISTS idx_transformer_positions_with_grid_geom ON transformer_positions_with_grid USING gist (geom);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_transformer_positions_with_grid_pk ON transformer_positions_with_grid (grid_result_id)
    """,
    "transformer_classified_with_grid": """
    CREATE MATERIALIZED VIEW IF NOT EXISTS transformer_classified_with_grid AS (
        SELECT 
            tc.*,
            gr.version_id,
            gr.kcid,
            gr.bcid,
            gr.plz,
            gr.country_code,
            gr.transformer_rated_power,
            gr.transformer_equipment_name,
            ed.s_max_kva,
            ed.max_i_a,
            ed.r_mohm_per_km,
            ed.x_mohm_per_km,
            ed.z_mohm_per_km,
            ed.cost_eur,
            ed.equipment_only_cost_eur,
            ed.installed_cost_eur,
            ed.typ AS equipment_type
        FROM transformer_classified tc
        JOIN grid_result gr ON tc.grid_result_id = gr.grid_result_id
        LEFT JOIN equipment_data ed 
            ON gr.version_id = ed.version_id 
            AND gr.transformer_equipment_name = ed.name
    );
    CREATE INDEX IF NOT EXISTS idx_transformer_classified_with_grid_geom ON transformer_classified_with_grid USING gist (geom);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_transformer_classified_with_grid_pk ON transformer_classified_with_grid (grid_result_id, classification_id)
    """,
    "buildings_result_with_grid": """
    CREATE MATERIALIZED VIEW IF NOT EXISTS buildings_result_with_grid AS (
        SELECT
            (br.version_id || '_' || br.osm_id) AS id,
            br.*,
            gr.kcid, gr.bcid, gr.plz, gr.country_code
        FROM buildings_result br
        JOIN grid_result gr ON br.grid_result_id = gr.grid_result_id
    );
    CREATE INDEX IF NOT EXISTS idx_buildings_result_with_grid_geom ON buildings_result_with_grid USING gist (geom);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_buildings_result_with_grid_pk ON buildings_result_with_grid (id)
    """,
    "lines_result_with_grid": """
    CREATE MATERIALIZED VIEW IF NOT EXISTS lines_result_with_grid AS (
        SELECT
            lr.lines_result_id as id,
            lr.grid_result_id,
            lr.geom,
            lr.line_name,
            lr.std_type,
            lr.from_bus,
            lr.to_bus,
            lr.length_km,
            gr.version_id, gr.kcid, gr.bcid, gr.plz, gr.country_code
        FROM lines_result lr
        JOIN grid_result gr ON lr.grid_result_id = gr.grid_result_id
    );
    CREATE INDEX IF NOT EXISTS idx_lines_result_with_grid_geom ON lines_result_with_grid USING gist (geom);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_lines_result_with_grid_pk ON lines_result_with_grid (id)
    """,
}

TEMP_CREATE_QUERIES = {
    "buildings_tem": """CREATE TABLE IF NOT EXISTS buildings_tem
    (
        osm_id varchar,
        country_code varchar(10) DEFAULT 'DE',
        area double precision,
        type varchar(80),
        f_class varchar(80),
        f_classes text,
        geom geometry(Geometry,3035),  -- needs to be geometry as multipoint & multipolygon get inserted here
        households_per_building integer,
        center geometry(Point,3035),
        peak_load_in_kw double precision,
        plz varchar(10),
        vertice_id bigint,
        bcid integer,
        kcid integer,
        floors integer,
        connection_point integer,
        address_street_id integer,
        construction_year text,
        height_max double precision,
        height_ground double precision,
        height_median double precision,
        floors_3dbag integer,
        bag_id varchar,
        energy_label varchar(5),
        energy_index double precision,
        cbs_population double precision,
        cbs_households double precision,
        cbs_avg_household_size double precision
    )""",
    "ways_tem": """CREATE TABLE IF NOT EXISTS ways_tem
    (
        clazz integer,
        source integer,
        target integer,
        cost double precision,
        reverse_cost double precision,
        geom geometry(LineString,3035),
        way_id integer,
        plz varchar(10),
        country_code varchar(10) DEFAULT 'DE'
    )""",
}

REFRESH_QUERIES = {
    "transformer_positions_with_grid": """
    REFRESH MATERIALIZED VIEW CONCURRENTLY transformer_positions_with_grid
    """,
    "transformer_classified_with_grid": """
    REFRESH MATERIALIZED VIEW CONCURRENTLY transformer_classified_with_grid
    """,
    "buildings_result_with_grid": """
    REFRESH MATERIALIZED VIEW CONCURRENTLY buildings_result_with_grid
    """,
    "lines_result_with_grid": """
    REFRESH MATERIALIZED VIEW CONCURRENTLY lines_result_with_grid
    """,
}

# Seed data for countries - must be inserted before other tables due to foreign keys
SEED_QUERIES = {
    "country": """
    INSERT INTO country (country_code, country_name, crs) VALUES
        -- Western Europe
        ('DE', 'Germany', 'EPSG:3035'),
        ('NL', 'Netherlands', 'EPSG:28992'),
        ('BE', 'Belgium', 'EPSG:3035'),
        ('LU', 'Luxembourg', 'EPSG:3035'),
        ('FR', 'France', 'EPSG:3035'),
        ('CH', 'Switzerland', 'EPSG:3035'),
        ('AT', 'Austria', 'EPSG:3035'),
        ('LI', 'Liechtenstein', 'EPSG:3035'),
        ('MC', 'Monaco', 'EPSG:3035'),
        -- Northern Europe
        ('DK', 'Denmark', 'EPSG:3035'),
        ('SE', 'Sweden', 'EPSG:3035'),
        ('NO', 'Norway', 'EPSG:3035'),
        ('FI', 'Finland', 'EPSG:3035'),
        ('IS', 'Iceland', 'EPSG:3035'),
        ('IE', 'Ireland', 'EPSG:3035'),
        ('GB', 'United Kingdom', 'EPSG:3035'),
        -- Southern Europe
        ('IT', 'Italy', 'EPSG:3035'),
        ('ES', 'Spain', 'EPSG:3035'),
        ('PT', 'Portugal', 'EPSG:3035'),
        ('GR', 'Greece', 'EPSG:3035'),
        ('MT', 'Malta', 'EPSG:3035'),
        ('CY', 'Cyprus', 'EPSG:3035'),
        ('AD', 'Andorra', 'EPSG:3035'),
        ('SM', 'San Marino', 'EPSG:3035'),
        ('VA', 'Vatican City', 'EPSG:3035'),
        -- Eastern Europe
        ('PL', 'Poland', 'EPSG:3035'),
        ('CZ', 'Czech Republic', 'EPSG:3035'),
        ('SK', 'Slovakia', 'EPSG:3035'),
        ('HU', 'Hungary', 'EPSG:3035'),
        ('RO', 'Romania', 'EPSG:3035'),
        ('BG', 'Bulgaria', 'EPSG:3035'),
        ('SI', 'Slovenia', 'EPSG:3035'),
        ('HR', 'Croatia', 'EPSG:3035'),
        ('BA', 'Bosnia and Herzegovina', 'EPSG:3035'),
        ('RS', 'Serbia', 'EPSG:3035'),
        ('ME', 'Montenegro', 'EPSG:3035'),
        ('MK', 'North Macedonia', 'EPSG:3035'),
        ('AL', 'Albania', 'EPSG:3035'),
        ('XK', 'Kosovo', 'EPSG:3035'),
        -- Baltic States
        ('EE', 'Estonia', 'EPSG:3035'),
        ('LV', 'Latvia', 'EPSG:3035'),
        ('LT', 'Lithuania', 'EPSG:3035'),
        -- Other
        ('UA', 'Ukraine', 'EPSG:3035'),
        ('MD', 'Moldova', 'EPSG:3035'),
        ('BY', 'Belarus', 'EPSG:3035')
    ON CONFLICT (country_code) DO NOTHING
    """,
}
